new_way/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from new_way.core.views import *
from django.contrib import admin

urlpatterns = patterns(
    'new_way.core.views',
    url(r'^$', 'home', name='home'),

    url(r'^brands/$', BrandList.as_view(), name='brand_list'),
    url(r'^models/$', ModelList.as_view(), name='model_list'),
    url(r'^vehicles/$', VehicleList.as_view(), name='vehicle_list'),
    url(r'^vehicles/(?P<pk>\d+)/$',
        VehicleDetail.as_view(), name='vehicle_detail'),

    url(r'^accessorys/$', AccessoryList.as_view(), name='accessory_list'),

    url(r'^dealerships/$', DealershipList.as_view(), name='dealership_list'),
    url(r'^stores/$', StoreList.as_view(), name='store_list'),
    url(r'^ordereds/$', OrderedList.as_view(), name='ordered_list'),
    url(r'^ordered/(?P<pk>\d+)/$',
        OrderedDetail.as_view(), name='ordered_detail'),

    url(r'^customer/add/$', CustomerCreate.as_view(), name='customer_add'),
    url(r'^ordered/add/$', OrderedCreate.as_view(), name='ordered_add'),

    url(r'^dashboard/$', Dashboard.as_view(), name='dashboard'),

    # url(r'^about/$', 'about', name='about'),
    # url(r'^contact/$', 'contact', name='contact'),
    url(r'^underconstruction/$', UnderConstruction.as_view(),
        name='under_construction'),
    url(r'^admin/', include(admin.site.urls), name='admin'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new_way/core/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.formats import number_format
from django.contrib.auth.models import User
# List of values for use in choices
from .lists import gender_list, treatment_list, type_address_list, uf_list, \
    type_phone_list, fueltype_list, transmissiontype_list, status_list


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(
        _('criado em'), auto_now_add=True, auto_now=False)
    modified_at = models.DateTimeField(
        _('modificado em'), auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(_(u'endereço'), max_length=80)
    complement = models.CharField(
        _('complemento'), max_length=80, blank=True, null=True)
    district = models.CharField(_('bairro'), max_length=80)
    city = models.CharField(_('cidade'), max_length=80)
    uf = models.CharField(_('UF'), max_length=2, choices=uf_list)
    cep = models.CharField(_('CEP'), max_length=9)

    class Meta:
        abstract = True


class Person(TimeStampedModel, Address):
    gender = models.CharField(_(u'gênero'), max_length=1, choices=gender_list)
    first_name = models.CharField(_('nome'), max_length=100)
    last_name = models.CharField(_('sobrenome'), max_length=100)
    cpf = models.CharField(_('CPF'), max_length=11, unique=True)
    birthday = models.DateField(_('data de nascimento'))
    email = models.EmailField(_('email'), blank=True)
    phone = models.CharField(
        _('telefone'), max_length=15, null=True, blank=True)
    cell = models.CharField(_('celular'), max_length=15, null=True, blank=True)

    class Meta:
        abstract = True
        ordering = ['first_name']

    def __str__(self):
        return self.first_name + " " + self.last_name
    full_name = property(__str__)


class Customer(Person):

    class Meta:
        verbose_name = _(u'cliente')
        verbose_name_plural = _(u'clientes')


class Employee(Person):
    user = models.OneToOneField(User)
    occupation = models.ForeignKey(
        "Occupation", verbose_name='cargo', related_name='employee_occupation')
    dealership = models.ForeignKey(
        "Dealership", verbose_name=u'concessionária', related_name='employee_dealership')
    comissioned = models.BooleanField(_('comissionado'), default=True)
    comission = models.DecimalField(
        _(u'comissão'), max_digits=6, decimal_places=2)

    class Meta:
        verbose_name = _(u'funcionário')
        verbose_name_plural = _(u'funcionários')


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class Occupation(models.Model):
    occupation = models.CharField(_('cargo'), max_length=50)

    class Meta:
        verbose_name = _('cargo')
        verbose_name_plural = _('cargos')

    def __str__(self):
        return self.occupation


class Dealership(Address):
    dealership = models.CharField(_(u'concessionária'), max_length=50)
    site = models.CharField(_('site'), max_length=100, null=True, blank=True)
    phone1 = models.CharField(
        _('telefone 1'), max_length=15, null=True, blank=True)
    phone2 = models.CharField(
        _('telefone 2'), max_length=15, null=True, blank=True)
    phone3 = models.CharField(
        _('telefone 3'), max_length=15, null=True, blank=True)

    class Meta:
        verbose_name = _(u'concessionária')
        verbose_name_plural = _(u'concessionárias')

    def __str__(self):
        return self.dealership


class DealershipDetail(models.Model):
    dealership = models.ForeignKey(
        "Dealership", verbose_name=u'concessionária', related_name='dealership_det')
    vehicle = models.ForeignKey(
        "Vehicle", verbose_name=u'veículo', related_name='vehicle_det')
    quantity_vehicle = models.PositiveIntegerField(_('quantidade'))

    def __str__(self):
        return self.dealership  # unicode(self.dealership)


class Brand(models.Model):
    brand = models.CharField(_('marca'), max_length=50, unique=True)
    photo = models.ImageField(upload_to='brands')

    class Meta:
        ordering = ['brand']
        verbose_name = u'marca'
        verbose_name_plural = u'marcas'

    def __str__(self):
        return self.brand

    def thumb(self):
        return '<img src="%s"/ width="70px">' % self.photo.url
    thumb.allow_tags = True


class Modell(models.Model):
    modell = models.CharField(_('modelo'), max_length=50, unique=True)
    brand = models.ForeignKey(
        "Brand", verbose_name=u'marca', related_name='model_brand')

    class Meta:
        ordering = ['modell']
        verbose_name = u'modelo'
        verbose_name_plural = u'modelos'

    def __str__(self):
        return self.modell


class Vehicle(models.Model):
    modell = models.ForeignKey(
        "Modell", verbose_name=u'modelo', related_name='vehicle_model')
    vehicle = models.CharField(_('veículo'), max_length=50, unique=True)
    # slug = models.SlugField(_('slug'))
    color = models.CharField(_('cor'), max_length=50)
    year_of_manufacture = models.PositiveIntegerField(_(u'ano de fabricação'))
    engine_power = models.DecimalField(
        _('motor'), max_digits=6, decimal_places=2)
    fueltype = models.CharField(
        _(u'tipo de combustível'), max_length=1, choices=fueltype_list)
    transmissiontype = models.CharField(
        _(u'tipo de câmbio'), max_length=1, choices=transmissiontype_list)
    power = models.CharField(_(u'potência'), max_length=30, default='-')
    price = models.DecimalField(_(u'preço'), max_digits=8, decimal_places=2)
    kit_fabric = models.ForeignKey(
        "Kit", verbose_name=u'kit de fábrica', related_name='vehicle_kit')
    photo_vehicle = models.ImageField(
        upload_to='vehicles', default='vehicles/car_700x300.jpg')

    class Meta:
        ordering = ['vehicle']
        verbose_name = u'veículo'
        verbose_name_plural = u'veículos'

    def __str__(self):
        return self.vehicle

    # clica no carro e retorna os detalhes dele
    def get_vehicle_url(self):
        return u"/vehicles/%i" % self.id

    def get_price(self):
        return u"R$ %s" % number_format(self.price, 2)

    def thumb(self):
        return '<img src="%s"/ width="70px">' % self.photo_vehicle.url
    thumb.allow_tags = True

    def image(self):
        return '<img src="%s"/ width="500px">' % self.photo_vehicle.url
    image.allow_tags = True


class Accessory(models.Model):
    accessory = models.CharField(_(u'accessório'), max_length=50)
    price_accessory = models.DecimalField(
        _(u'preço'), max_digits=8, decimal_places=2)
    photo_accessory = models.ImageField(
        upload_to='accessorys', blank=True, null=True)

    class Meta:
        ordering = ['accessory']
        verbose_name = u'accessório'
        verbose_name_plural = u'accessórios'

    def __str__(self):
        return self.accessory

    def get_price(self):
        return u"R$ %s" % number_format(self.price_accessory, 2)

    def thumb(self):
        return '<img src="%s"/ width="70px">' % self.photo_accessory.url
    thumb.allow_tags = True

    def image(self):
        return '<img src="%s"/ width="500px">' % self.photo_accessory.url
    image.allow_tags = True


class Kit(models.Model):
    kit = models.CharField(max_length=50)

    class Meta:
        ordering = ['kit']
        verbose_name = u'kit'
        verbose_name_plural = u'kits'

    def __str__(self):
        return self.kit


class KitDetail(models.Model):
    kit = models.ForeignKey("Kit", verbose_name='kit', related_name='kit_det')
    accessory = models.ForeignKey(
        "Accessory", verbose_name=u'accessório', related_name='accessory_kit')
    quantity_accessory = models.PositiveIntegerField(_('quantidade'))

    def __str__(self):
        return str(self.kit)


class Store(models.Model):
    store = models.CharField(_(u'estabelecimento'), max_length=65)
    phone = models.CharField(_('telefone'), max_length=15, blank=True)
    city = models.CharField(_('cidade'), max_length=80, blank=True)
    uf = models.CharField(_('UF'), max_length=2, choices=uf_list)

    class Meta:
        ordering = ['store']
        verbose_name = u'estabelecimento'
        verbose_name_plural = u'estabelecimentos'

    def __str__(self):
        return self.store


class Kiosk(models.Model):
    kiosk = models.CharField(_(u'quiosque'), max_length=50)
    store = models.ForeignKey(
        "Store", verbose_name='estabelecimento', related_name='kiosk_store')

    class Meta:
        ordering = ['kiosk']
        verbose_name = u'quiosque'
        verbose_name_plural = u'quiosques'

    def __str__(self):
        return self.kiosk


class Ordered(TimeStampedModel):
    customer = models.ForeignKey("Customer", verbose_name='cliente')
    # employee = models.ForeignKey("Employee", verbose_name=u'funcionário')
    vehicle = models.ForeignKey("Vehicle", verbose_name=u'veículo')
    kit_optional = models.ForeignKey("Kit", verbose_name='kit opcional')
    dealership = models.ManyToManyField(
        "Dealership", verbose_name=u'concessionária')
    kiosk = models.ForeignKey("Kiosk", verbose_name='quiosque')
    status = models.CharField(max_length=2, choices=status_list, default='p')

    class Meta:
        ordering = ['-id']
        verbose_name = u'pedido'
        verbose_name_plural = u'pedidos'

    def __str__(self):
        return str(self.id)

    def get_detalhe(self):
        return u"/ordered/%i" % self.id

new_way/core/forms.py
from django import forms
from .models import Customer, Ordered
from .lists import gender_list, uf_list


class CustomerForm(forms.ModelForm):
    gender = forms.ChoiceField(
        label='Sexo', choices=gender_list, initial='M', widget=forms.RadioSelect)

    class Meta:
        model = Customer
        fields = '__all__'


class OrderedForm(forms.ModelForm):

    class Meta:
        model = Ordered
        fields = '__all__'

new_way/core/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic import CreateView, TemplateView, ListView, DetailView
from .models import Customer, Dealership, Address, Brand, Modell, Vehicle, Store, Ordered, Accessory
from .forms import CustomerForm
from new_way.core.managers import VehicleMixin, CountMixin


def home(request):
    return render(request, 'index.html')


class CustomerCreate(CreateView):
    template_name = 'core/person/customer_create_form.html'
    form_class = CustomerForm
    success_url = reverse_lazy('home')


class BrandList(ListView):
    template_name = 'core/vehicle/brand_list.html'
    model = Brand


class ModelList(ListView):
    template_name = 'core/vehicle/model_list.html'
    model = Modell
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(ModelList, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        models = Modell.objects.all()
        q = self.request.GET.get('search_box')
        if q is not None:
            models = models.filter(modell__istartswith=q)
        return models


class VehicleList(ListView):
    template_name = 'core/vehicle/vehicle_list.html'
    model = Vehicle
    paginate_by = 15

    def get_queryset(self):
        cars = Vehicle.objects.all()
        q = self.request.GET.get('search_box')
        if q is not None:
            cars = cars.filter(vehicle__icontains=q)
        return cars


class VehicleDetail(DetailView):
    template_name = 'core/vehicle/vehicle_detail.html'
    model = Vehicle

    def get_context_data(self, **kwargs):
        context = super(VehicleDetail, self).get_context_data(**kwargs)
        vehicle = Vehicle.objects.get(pk=self.kwargs['pk'])
        return context


class AccessoryList(ListView):
    template_name = 'core/vehicle/accessory_list.html'
    model = Accessory
    paginate_by = 12

    def get_queryset(self):
        accessorys = Accessory.objects.all()
        q = self.request.GET.get('search_box')
        if q is not None:
            accessorys = accessorys.filter(accessory__istartswith=q)
        return accessorys


class DealershipList(ListView):
    template_name = 'core/dealership/dealership_list.html'
    model = Dealership
    paginate_by = 10

    def get_queryset(self):
        dealerships = Dealership.objects.all()
        q = self.request.GET.get('search_box')
        if q is not None:
            dealerships = dealerships.filter(dealership__istartswith=q)
        return dealerships


class StoreList(ListView):
    template_name = 'core/store/store_list.html'
    model = Store
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(StoreList, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        stores = Store.objects.all()
        q = self.request.GET.get('search_box')
        if q is not None:
            stores = stores.filter(
                Q(store__icontains=q) | Q(city__icontains=q))
        return stores


class Dashboard(VehicleMixin, CountMixin, TemplateView):
    template_name = 'core/dashboard.html'


# @login_required
class OrderedCreate(CreateView):
    template_name = 'core/ordered/ordered_create_form.html'
    model = Ordered
    success_url = reverse_lazy('vehicle_list')  # 'ordered_list'


class OrderedList(ListView):
    template_name = 'core/ordered/ordered_list.html'
    model = Ordered
    paginate_by = 10


class OrderedDetail(DetailView):
    template_name = 'core/ordered/ordered_detail.html'
    model = Ordered

    def get_context_data(self, **kwargs):
        context = super(OrderedDetail, self).get_context_data(**kwargs)
        ordered = Ordered.objects.get(pk=self.kwargs['pk'])
        return context


class UnderConstruction(TemplateView):
    template_name = "core/under_construction.html"

'''
https://www.technovelty.org/web/skipping-pages-with-djangocorepaginator.html
'''

new_way/core/templates/core/vehicle/accessory_list.html
{% extends "base.html" %}

{% block content %}

    <form class="navbar-form navbar-right" action="." method="get">
        <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    </form>
	
    <div class="page-header">
        <h2>Escolha seu acessório <font size="3">(valores fictícios)</font></h2>
    </div>

    <div class="container initial-p">
        <div class="row">
		    {% if object_list %}
				{% for accessory in object_list %}

		            <div class="col-md-4 portfolio-item">
		                    <img class="img-responsive" src="{{ accessory.photo_accessory.url }}" height="50px">
		                <h3>{{ accessory.accessory }}</h3>
		                <h4 class="highlight">{{ accessory.get_price }}</h4>
		            </div>

	        {% endfor %}
	        {% else %}
		        <p class="alert alert-warning">Sem itens na lista.</p>
		    {% endif %}
	    </div>
    </div>

<!-- pagination -->
{% include "pagination.html" %}

{% endblock content %}

new_way/core/templates/core/vehicle/brand_list.html
{% extends "base.html" %}

{% block content %}
	
    <div class="page-header">
        <h2>Marcas</h2>
    </div>

	<div class="row">
        {% if object_list %}
            {% for brand in object_list %}
                <div class="col-md-25 portfolio-item">
                <a href="#">
                    <img class="img-responsive center" src="{{ brand.photo.url }}">
                    <p class="center">{{ brand.brand }}</p>
                </a>
            </div>
            {% endfor %}
        {% else %}
            <p class="alert alert-warning">Sem itens na lista.</p>
        {% endif %}
    </div>


{% endblock content %}

new_way/core/templates/core/vehicle/model_list.html
{% extends "base.html" %}

{% block content %}

    <form class="navbar-form navbar-right" action="." method="get">
        <!-- add -->
<!--         <a href="#"> -->
<!--             <button id="new_sale" type="button" class="btn btn-primary"> -->
<!--                 <span class="glyphicon glyphicon-plus"></span> Adicionar -->
<!--             </button> -->
<!--         </a> -->
        <!-- search form -->
        <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    </form>
	
    <div class="page-header">
        <h2>Modelos</h2>
    </div>

	<div>
	    {% if object_list %}
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Marca</th>
						<th>Modelo</th>
					</tr>
				</thead>
				<tbody>
			    	{% for modell in object_list %}
			    		<tr>
			    			<td>{{ modell.brand }}</td>
			    			<td>{{ modell.modell }}</td>
			    		</tr>
			    	{% endfor %}
				</tbody>
			</table>
	    {% else %}
	        <p class="alert alert-warning">Sem itens na lista.</p>
	    {% endif %}
	</div>

<!-- pagination -->
{% include "pagination.html" %}

{% endblock content %}

new_way/core/templates/core/vehicle/vehicle_detail.html
{% extends "base.html" %}

{% block title %}
	<title>Vehicle Detail</title>
{% endblock title %}

{% block content %}

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">{{ object.vehicle }}
                    <small></small>
                </h1>
            </div>

        </div>

        <div class="row">

            <div class="col-md-8">
                <img class="img-responsive" src="{{ vehicle.photo_vehicle.url }}">
                <div class="ratings">
                    <!-- <p class="pull-right">3 reviews</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                        4.0 stars
                    </p> -->
                </div>
            </div>

            <div class="col-md-4">
                <!-- <h3>Titulo</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
                <h3>Detalhes do carro</h3> -->
                <ul class="list-group">
                    <li class="list-group-item">Motor: {{ object.engine_power }}</li>
                    <li class="list-group-item">Potência: {{ object.power }} cv</li>
                    <li class="list-group-item">Cor: {{ object.color }}</li>
                    <li class="list-group-item">Combustível: {{ object.get_fueltype_display }}</li>
                    <li class="list-group-item">Transmissão: {{ object.get_transmissiontype_display }}</li>
                </ul>
                <h2>{{ object.get_price }}</h2>
                <a class="btn btn-lg btn-primary" href="{% url 'ordered_add' %}">Monte seu carro</a>
            </div>

        </div>

        <!-- <div class="row">

            <div class="col-lg-12">
                <h3 class="page-header">Acessórios <small>Usar carousel</small></h3>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="{{ STATIC_URL }}img/car_500x300.jpg">
                </a>
                <p><h4>acessório 1</h4></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="{{ STATIC_URL }}img/car_500x300.jpg">
                </a>
                <p><h4>acessório 2</h4></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="{{ STATIC_URL }}img/car_500x300.jpg">
                </a>
                <p><h4>acessório 3</h4></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="{{ STATIC_URL }}img/car_500x300.jpg">
                </a>
                <p><h4>acessório 4</h4></p>
            </div>

        </div> -->

    </div>

{% endblock content %}

new_way/core/templates/core/vehicle/vehicle_list.html
{% extends "base.html" %}

{% block content %}

    <form class="navbar-form navbar-right" action="." method="get">
        <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    </form>
	
    <div class="page-header">
        <h2>Escolha seu carro <font size="3">(valores fictícios)</font></h2>
    </div>

    <div class="container initial-p">
        <div class="row">
		    {% if object_list %}
				{% for vehicle in object_list %}

		            <div class="col-md-4 portfolio-item">
		                <a href="{{ vehicle.get_vehicle_url }}">
		                    <img class="img-responsive" src="{{ vehicle.photo_vehicle.url }}" height="50px">
		                </a>
		                <!-- <div class="ratings">
		                    <p class="pull-right">3 reviews</p>
		                    <p>
		                        <span class="glyphicon glyphicon-star"></span>
		                        <span class="glyphicon glyphicon-star"></span>
		                        <span class="glyphicon glyphicon-star"></span>
		                        <span class="glyphicon glyphicon-star"></span>
		                        <span class="glyphicon glyphicon-star-empty"></span>
		                        4.0 stars
		                    </p>
		                </div> -->
		                <h3><a href="{{ vehicle.get_vehicle_url }}">{{ vehicle.vehicle }}</a>
		                </h3>
		                <div class="pull-right">
			                <a class="btn btn-primary" href="{% url 'ordered_add' %}">Monte seu carro <span class="glyphicon glyphicon-plus"></span></a>
		                </div>
		                <p>A partir de</p>
		                <h4 class="highlight">{{ vehicle.get_price }}</h4>
		            </div>

	        {% endfor %}
	        {% else %}
		        <p class="alert alert-warning">Sem itens na lista.</p>
		    {% endif %}
	    </div>
    </div>

        <hr>

        <div class="row">
<!--			<table class="table table-striped">
				<thead>
					<tr>
						<th>Foto</th>
						<th>Carro</th>
						<th>Modelo</th>
						<th>Cor</th>
						<th>Ano</th>
						<th>Potência</th>
						<th>Combustível</th>
						<th>Câmbio</th>
						<th>Freio</th>
						<th>Roda</th>
						<th>Desempenho</th>
						<th>Porta-malas</th>
						<th>A partir de</th>
					</tr>
				</thead>
				<tbody>
			    	{% for vehicle in object_list %}
			    		<tr>
							<td><img src="{{ vehicle.photo_vehicle.url }}" height="30px" width="50px"></td>
							<td>{{ vehicle.vehicle }}</td>
							<td>{{ vehicle.modell }}</td>
							<td>{{ vehicle.color }}</td>
							<td>{{ vehicle.year_of_manufacture }}</td>
							<td>{{ vehicle.engine_power }}</td>
							<td>{{ vehicle.get_fueltype_display }}</td>
							<td>{{ vehicle.get_transmissiontype_display }}</td>
							<td>{{ vehicle.wheel }}</td>
							<td>{{ vehicle.tire }}</td>
							<td>{{ vehicle.performance }}</td>
							<td>{{ vehicle.trunk }}</td>
							<td>{{ vehicle.price }}</td>
			    		</tr>
			    	{% endfor %}
				</tbody>
			</table>
	     else 
	        <p class="alert alert-warning">Sem itens na lista.</p>
	     endif  -->
	</div>

<!-- pagination -->
{% include "pagination.html" %}

{% endblock content %}